### ISSUE TITLE
Missing Favourites

### ISSUE THREAD

**Issue by SkyBird1980** [manuelm/pvr.dvbviewer#14]
if you have some regional pvr channels from time to time a program is missing.
it seams a addon problem, because the api gives the correct channels.
if i delete the channel in dvbviewer favourites and add them again they are visible after restart of the media server service.
i will attach the /api/getchannelsxml.html?favonly=1
i use "only favourites" in pvr addon.

[getchannelsxml.xml.txt](https://github.com/manuelm/pvr.dvbviewer/files/981712/getchannelsxml.xml.txt)
pvr list inside kodi:
![screenshot005](https://cloud.githubusercontent.com/assets/4501443/25782666/80e466aa-334f-11e7-828f-876affc47054.png)

kodi.log (no debug):

[kodi.log.txt](https://github.com/manuelm/pvr.dvbviewer/files/981714/kodi.log.txt)

NDR FS SH HD is the missing channel.

**Comment by manuelm** [comment]
See `Some channels are still missing *and* I'm using favourites only` @ http://forum.kodi.tv/showthread.php?tid=221531&pid=1957396#pid1957396

So right now this is expected behavior. The requirement for keeping your favourites in sync with your channel list (which might change automatically) will change as soon as I pull the merged channel+favourites list from the backend. But this will bump the required RS version plus it's only for non-local favourites.

**Comment by SkyBird1980** [comment]
sorry, didn't see it in FAQ ... i'm just blind.
