### ISSUE TITLE
Recordings playback stopping on Nvidia Shield via Ethernet

### ISSUE THREAD

**Issue by cipher2k** [manuelm/pvr.dvbviewer#40]
Since a few months playback of recordings does not work through PVR plugin does not work on Nvidia Shield when connected via Ethernet.
The playback then stops after a few seconds.
If I turn off Ethernet and connect via Wifi then playback of recordings works without any issues.
Playing back recordings through the file manager in Kodi works also without any issues via Ethernet and Wifi. This was my workaround for the past months.

But now I realized that I am not the only with the same problem.

This is the moment when the playback stops:

`2019-03-17 23:04:07.720 T:22099   DEBUG: SetCodecControl 0->20000000
2019-03-17 23:04:07.821 T:22099    INFO: CVideoPlayerVideo - Stillframe detected, switching to forced 50.000000 fps
2019-03-17 23:04:07.821 T:22099   DEBUG: CPtsTracker: pattern lost on diff 100000.000000, number of losses 1
2019-03-17 23:04:07.827 T:19347   DEBUG: PrepareNextRender: frameOnScreen: 27762638.616239 renderPts: 27668270.888525 nextFramePts: 27318266.222222 -> diff: 350004.666303  render: 1 forceNext: 0
2019-03-17 23:04:10.610 T:22089   DEBUG: ffmpeg[205C70A4F0]: [mpegts] pid=17de pes_code=0x1e0
2019-03-17 23:04:10.610 T:22089   DEBUG: ffmpeg[205C70A4F0]: [NULL] ct_type:0 pic_struct:0
2019-03-17 23:04:10.610 T:22099    INFO: CVideoPlayerVideo - Stillframe left, switching to normal playback
2019-03-17 23:04:10.610 T:22089   DEBUG: CVideoPlayer::SetCaching - caching state 1
2019-03-17 23:04:10.611 T:22099   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 0
2019-03-17 23:04:10.611 T:22090   DEBUG: CDVDAudio::Pause - pausing audio stream
2019-03-17 23:04:10.611 T:22089   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
2019-03-17 23:04:10.611 T:22099   DEBUG: SetCodecControl 20000000->4000000
2019-03-17 23:04:10.611 T:22099   DEBUG: CDVDVideoCodecAndroidMediaCodec::AddData dts:27358244.22 pts:27378266.44 sz:245 indexBuffer:6 current state (4)
2019-03-17 23:04:10.612 T:22099   ERROR: CDVDVideoCodecAndroidMediaCodec::AddData error(-10000)
2019-03-17 23:04:10.612 T:22099   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 0`

[kodi.log](https://github.com/manuelm/pvr.dvbviewer/files/2975784/kodi.log)

**Comment by manuelm** [comment]
See https://forum.kodi.tv/showthread.php?tid=341945

**Comment by cipher2k** [comment]
Ok, if it can not be the fault of the PVR plugin then it has to be the fault of DVBViewer Media Server?

**Comment by manuelm** [comment]
Never said that. Although there is a recent regression in DMS which reduces streaming bandwith on Windows 7 which will be fixed in the upcoming version. No idea if you're using Windows 7 though.

As a first test try to play the URL `http://192.168.90.3:10101/upnp/recordings/584.ts` in Kodi and see if it stalls aswell.

**Comment by manuelm** [comment]
Oh and try to downgrade DMS to something lower than 2.1.3. Maybe it's the regression (Windows dynamic send buffer handling) nevertheless.

**Comment by cipher2k** [comment]
My DMS is running on Windows Server 2016.
Playing the URL via a STRM file does also stall after a few seconds.

**Comment by manuelm** [comment]
Mh. Try to play with the XFILE flags in https://github.com/manuelm/pvr.dvbviewer/blob/master/src/RecordingReader.cpp#L20 and see if they make any difference. You can find all of them here: https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/IFileTypes.h#L13

Other than that I don't have any meaningful clues.

**Comment by cipher2k** [comment]
How do I use those XFILE flags?

**Comment by manuelm** [comment]
By ORing them? I'm already using two of the flags. Just look at the line and try to replace them with every possible combination. Since there are 9 flags there are _only_ 512 combinations ^^. But I'm sure you can rule out some of them.

Btw If you clone my repo and create yourself an AppVeyor account you don't even need a build environment. Just edit the file online. AppVeyor should spit out linux + windows builds.

This information should get you started. Good luck.

**Comment by manuelm** [comment]
Things you might check out first:
* remove `READ_NO_CACHE`
* add `READ_TRUNCATED` and/or `READ_CHUNKED`

Oh and try to play with `Stream read chunk size` in the PVR settings beforehand.

**Comment by cipher2k** [comment]
changing the stream read chunk size in the plugin settings does not help.

**Comment by bernhardberger** [comment]
Having the same issues since Leia Beta versions (was fine in Nightlies and Alphas as far as I can remember..). Can't playback a recording through the PVR:// protocol (neither in the "Videos" plugin, nor via "Live TV/Recordings". Wasn't an issue in Krypton.. Recording also plays just fine when played through my Samba share. (WiFi or Ethernet doesn't matter).

If I can help you with debugging I'd be happy too.. as far as I remember we're from about the same region..? (think you were involved with G:n/G:s too if I remember correctly..?) Worst case I could bring over my Shield for a debug session..

**Comment by manuelm** [comment]
Had to think really really hard what `G:n/G:s` meant. It's been a while…

As explained above you can fork my repo, modify the flags step by step (even using the webeditor) and let appveyor autobuild the PVR. Then try the downloadable zip on your device.

There hasn't been any changes on the PVR side in the Beta phase as far as I can see. However there could have been a bug fix in Kodi Core which changes behavior on my side.

Regarding the debug session: If I agree I'd rather prefer if you leave me the device. I'm not that familiar with Android debugging and compilation. So it might take some time. And my free time is rather limited these days.

**Comment by bernhardberger** [comment]
Looks like something got fixed in Kodi 18.3..

I think this can be closed..
