### ISSUE TITLE
WoL not practical with Android TV client

### ISSUE THREAD

**Issue by CiNcH83** [manuelm/pvr.dvbviewer#41]
I now tried the WoL feature and found it not to be practical with Android TV as client. The problem is that Android TV wakes up every 5 minutes to do... well... something. According to Android's alarmmanager it is Google's Cloud Massaging setting up periodic RTC timers. In fact every app is able to do that. So whenever the system wakes up, also Kodi in the background reconnects to the RS/DMS which effectively wakes up the server in case WoL is activated.
Kodi might also run in the background with the user only using Netflix or Prime Video, being a common use-case on a smart TV. With the current WoL implementation, it will also keep the RS/DMS alive.

My idea to solve it would be to only send the magic packet on Kodi startup plus when a channel is actively being tuned and the client is in the disconnected state. I just tested it and channels are also available in the disconnected state when there has already been a connection to the backend during Kodi runtime.

Thoughts?

**Comment by manuelm** [comment]
The PVR is fetching EPG, timer and recording updates periodically. If *any* connection fails it marks the backend as unreachable and information disappears from Kodi (e.g. recordings). I'm actually surprised you still can see the channels if the backend is unreachable. Not sure if this is how it's meant to be though. Maybe @ksooo can clarify on this.

However if I change the code so that the periodic tasks are only performed if the backend is reachable this will result in a couple of other drawbacks. e.g. the wake ups won't be fast enough. So you press switch channel but the call will immediately fail. Then you have to wait until the PVR notices that the backend is reachable again and you can proceed. The same will happen for all other PVR related tasks.
Another issue is the backend will go to standby way more often than before. So regular EPG updates might not happen anymore.

Because of this I'm really reluctant to change the current behavior. If you don't need the backend up and running you can disable the PVRs WoL and simply use Kodis WoL addon.

Also to me this sounds like an issue about Kodi Core on Android. Not about the PVR.
